site_name: FM Lab Documentation
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Hitchhikers Guide to the FM Lab: hitchhikers_guide.md
  - How to ...?: how_to.md
markdown_extensions:
  - attr_list
extra_css:
  - css/extra.css
